### ISSUE TITLE
Ability to Re-Stream 

### ISSUE THREAD

**Issue by jarodium** [Nycrera/icy-streamer#3]
## Detailed Description

Mainly the ability to pickup a stream from Shoutcast/IceCast and re-serve it via HTTPS.

## Context

It's important because Shoutcast does not support streaming to HTTPS. By serving an http:// based url ( shoutcast ) on an https:// website, Chrome complains the website is not safe.

For letting users know, in the end, that the website providing the stream is safe.

## Your Environment

* Version used:
* Environment name and software version (e.g. Ezstream 0.6.0 with Node.js 10.15.1):
* Server type and version:
* Operating System and version:
* Link to your project:

**Comment by Nycrera** [comment]
Hi, I am not sure if ezstream can pick up a stream and reserve it. It's been a while until the time I used this though.
Also, I don't think this is the right way to achieve a secure stream over HTTPS.

What you can do is using a Reverse Proxy. For example Nginx or Apache (probably with mod_proxy).
Here's a quick example on how to setup reverse proxy with Nginx.
on your sites-available folder, you need a configuration file as:
```nginx
server {
        listen  443 ssl;
        server_name yourwebsite.com;

        ssl_certificate     /etc/ssl/certs/server.crt;
        ssl_certificate_key /etc/ssl/certs/server.key;

        location /stream { 
           proxy_pass http://shoutcaststream.com:8000/mount; 
        }
}
```
This should redirect any requests to `https://yourwebsite.com/stream` from `http://shoutcaststream.com:8000/mount` with an extra security layer.

If you want to Chrome to not complain about your security. You would need a valid SSL certificate though.

Some further reading:
https://www.scaleway.com/en/docs/how-to-configure-nginx-reverse-proxy/
https://stackoverflow.com/questions/37011675/web-radio-stream-proxying
